"""Create users table

Revision ID: a27a2d8ab6cb
Revises: 
Create Date: 2025-03-20 11:45:59.368532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a27a2d8ab6cb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('employees', 'position')
    op.create_index(op.f('ix_leave_id'), 'leave', ['id'], unique=False)
    op.drop_constraint('leave_employee_id_fkey', 'leave', type_='foreignkey')
    op.create_foreign_key(None, 'leave', 'employees', ['employee_id'], ['id'])
    op.create_index(op.f('ix_payroll_id'), 'payroll', ['id'], unique=False)
    op.drop_constraint('payroll_employee_id_fkey', 'payroll', type_='foreignkey')
    op.create_foreign_key(None, 'payroll', 'employees', ['employee_id'], ['id'])
    op.create_index(op.f('ix_time_tracking_id'), 'time_tracking', ['id'], unique=False)
    op.drop_constraint('time_tracking_employee_id_fkey', 'time_tracking', type_='foreignkey')
    op.create_foreign_key(None, 'time_tracking', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'time_tracking', type_='foreignkey')
    op.create_foreign_key('time_tracking_employee_id_fkey', 'time_tracking', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_time_tracking_id'), table_name='time_tracking')
    op.drop_constraint(None, 'payroll', type_='foreignkey')
    op.create_foreign_key('payroll_employee_id_fkey', 'payroll', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_payroll_id'), table_name='payroll')
    op.drop_constraint(None, 'leave', type_='foreignkey')
    op.create_foreign_key('leave_employee_id_fkey', 'leave', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_leave_id'), table_name='leave')
    op.add_column('employees', sa.Column('position', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
